### ISSUE TITLE
error reports

### ISSUE THREAD

**Issue by vivaxy** [event-lab/preload-images#8]

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-01 14:43:25.393 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v0.12.7",
"argv": [
    "node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.8",

"error": [
    "ReferenceError: asdfasfd is not defined",
    "    at main (/Users/vivaxy/code/github/preload-images/index.js:65:9)",
    "    at Object.<anonymous> (/Users/vivaxy/code/github/preload-images/index.js:121:1)",
    "    at Module._compile (module.js:460:26)",
    "    at Object.Module._extensions..js (module.js:478:10)",
    "    at Module.load (module.js:355:32)",
    "    at Function.Module._load (module.js:310:12)",
    "    at Function.Module.runMain (module.js:501:10)",
    "    at startup (node.js:129:16)",
    "    at node.js:814:3"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-15 17:01:50.103 +0800",
"arch": "x64",
"platform": "win32",
"node-version": "v0.12.7",
"argv": [
    "node",
    "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js"
],
"cwd": "C:\\Users\\Administrator",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.9",

"error": [
    "Error: EPERM, operation not permitted 'C:\\Users\\Administrator\\AppData\\Local\\Application Data'",
    "    at Error (native)",
    "    at Object.fs.readdirSync (fs.js:761:18)",
    "    at GlobSync._readdir (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:275:41)",
    "    at GlobSync._readdirInGlobStar (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:254:20)",
    "    at GlobSync._readdir (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:263:17)",
    "    at GlobSync._processReaddir (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:135:22)",
    "    at GlobSync._process (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:130:10)",
    "    at GlobSync._processGlobStar (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:360:10)",
    "    at GlobSync._process (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:128:10)",
    "    at GlobSync._processGlobStar (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:363:10)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-23 18:33:35.318 +0800",
"arch": "x64",
"platform": "win32",
"node-version": "v0.12.7",
"argv": [
    "node",
    "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js"
],
"cwd": "E:\\dp_myWorkResult\\myDemo\\2403",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.9",

"error": [
    "Error: ENOENT, no such file or directory 'E:\\dp_myWorkResult\\myDemo\\2403\\css\\img\\preload'",
    "    at Error (native)",
    "    at Object.fs.mkdirSync (fs.js:747:18)",
    "    at imageBuilder (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\lib\\image-builder.js:26:16)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:108:21)",
    "    at exports.each (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\cheerio\\lib\\api\\traversing.js:293:24)",
    "    at C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:107:25",
    "    at Array.forEach (native)",
    "    at main (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:99:19)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:126:1)",
    "    at Module._compile (module.js:460:26)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-23 18:34:00.421 +0800",
"arch": "x64",
"platform": "win32",
"node-version": "v0.12.7",
"argv": [
    "node",
    "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js"
],
"cwd": "E:\\dp_myWorkResult\\myDemo\\2403",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.9",

"error": [
    "Error: ENOENT, no such file or directory 'E:\\dp_myWorkResult\\myDemo\\2403\\css\\img\\preload'",
    "    at Error (native)",
    "    at Object.fs.mkdirSync (fs.js:747:18)",
    "    at imageBuilder (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\lib\\image-builder.js:26:16)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:108:21)",
    "    at exports.each (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\cheerio\\lib\\api\\traversing.js:293:24)",
    "    at C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:107:25",
    "    at Array.forEach (native)",
    "    at main (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:99:19)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:126:1)",
    "    at Module._compile (module.js:460:26)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-23 18:36:19.620 +0800",
"arch": "x64",
"platform": "win32",
"node-version": "v0.12.7",
"argv": [
    "node",
    "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js"
],
"cwd": "E:\\dp_myWorkResult\\myDemo\\2403",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.9",

"error": [
    "Error: ENOENT, no such file or directory 'E:\\dp_myWorkResult\\myDemo\\2403\\css\\img\\preload'",
    "    at Error (native)",
    "    at Object.fs.mkdirSync (fs.js:747:18)",
    "    at imageBuilder (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\lib\\image-builder.js:26:16)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:108:21)",
    "    at exports.each (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\cheerio\\lib\\api\\traversing.js:293:24)",
    "    at C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:107:25",
    "    at Array.forEach (native)",
    "    at main (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:99:19)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:126:1)",
    "    at Module._compile (module.js:460:26)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-23 18:36:34.376 +0800",
"arch": "x64",
"platform": "win32",
"node-version": "v0.12.7",
"argv": [
    "node",
    "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js"
],
"cwd": "E:\\dp_myWorkResult\\myDemo\\2403",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.9",

"error": [
    "Error: ENOENT, no such file or directory 'E:\\dp_myWorkResult\\myDemo\\2403\\css\\img\\preload'",
    "    at Error (native)",
    "    at Object.fs.mkdirSync (fs.js:747:18)",
    "    at imageBuilder (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\lib\\image-builder.js:26:16)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:108:21)",
    "    at exports.each (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\cheerio\\lib\\api\\traversing.js:293:24)",
    "    at C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:107:25",
    "    at Array.forEach (native)",
    "    at main (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:99:19)",
    "    at Object.<anonymous> (C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js:126:1)",
    "    at Module._compile (module.js:460:26)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-24 16:50:26.763 +0800",
"arch": "ia32",
"platform": "win32",
"node-version": "v0.10.30",
"argv": [
    "c:\\Program Files (x86)\\nodejs\\node.exe",
    "f:\\develop\\preload-images\\index.js"
],
"cwd": "f:\\develop\\preload-images\\demo",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.9",

"error": [
    "SyntaxError: Invalid regular expression: /\\/: \\ at end of pattern",
    "    at new RegExp (<anonymous>)",
    "    at normalizePath (f:\\develop\\preload-images\\lib\\image-builder.js:15:37)",
    "    at imageBuilder (f:\\develop\\preload-images\\lib\\image-builder.js:44:50)",
    "    at Object.<anonymous> (f:\\develop\\preload-images\\index.js:108:21)",
    "    at exports.each (f:\\develop\\preload-images\\node_modules\\cheerio\\lib\\api\\traversing.js:293:24)",
    "    at f:\\develop\\preload-images\\index.js:107:25",
    "    at Array.forEach (native)",
    "    at main (f:\\develop\\preload-images\\index.js:99:19)",
    "    at Object.<anonymous> (f:\\develop\\preload-images\\index.js:126:1)",
    "    at Module._compile (module.js:456:26)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-29 17:03:15.577 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v0.12.7",
"argv": [
    "node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images/demo",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.10",

"error": [
    "Error: cb must be a function",
    "    at Jimp.throwError (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:39:43)",
    "    at new Jimp (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:142:24)",
    "    at imageBuilder (/Users/vivaxy/code/github/preload-images/lib/image-builder.js:41:13)",
    "    at Object.<anonymous> (/Users/vivaxy/code/github/preload-images/index.js:108:21)",
    "    at exports.each (/Users/vivaxy/code/github/preload-images/node_modules/cheerio/lib/api/traversing.js:293:24)",
    "    at /Users/vivaxy/code/github/preload-images/index.js:107:25",
    "    at Array.forEach (native)",
    "    at main (/Users/vivaxy/code/github/preload-images/index.js:99:19)",
    "    at Object.<anonymous> (/Users/vivaxy/code/github/preload-images/index.js:126:1)",
    "    at Module._compile (module.js:460:26)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-29 17:04:00.097 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v0.12.7",
"argv": [
    "node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images/demo",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.10",

"error": [
    "Error: w and h must be numbers",
    "    at Jimp.throwError (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:39:43)",
    "    at Jimp.resize (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:1010:20)",
    "    at Jimp.<anonymous> (/Users/vivaxy/code/github/preload-images/lib/image-builder.js:43:22)",
    "    at Jimp.parseBitmap (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:241:23)",
    "    at /Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:148:29",
    "    at fs.js:334:14",
    "    at FSReqWrap.oncomplete (fs.js:95:15)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-29 17:04:00.166 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v0.12.7",
"argv": [
    "node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images/demo",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.10",

"error": [
    "Error: w and h must be numbers",
    "    at Jimp.throwError (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:39:43)",
    "    at Jimp.resize (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:1010:20)",
    "    at Jimp.<anonymous> (/Users/vivaxy/code/github/preload-images/lib/image-builder.js:43:22)",
    "    at Jimp.parseBitmap (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:241:23)",
    "    at /Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:148:29",
    "    at fs.js:334:14",
    "    at FSReqWrap.oncomplete (fs.js:95:15)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-29 17:04:00.200 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v0.12.7",
"argv": [
    "node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images/demo",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.10",

"error": [
    "Error: w and h must be numbers",
    "    at Jimp.throwError (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:39:43)",
    "    at Jimp.resize (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:1010:20)",
    "    at Jimp.<anonymous> (/Users/vivaxy/code/github/preload-images/lib/image-builder.js:43:22)",
    "    at Jimp.parseBitmap (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:241:23)",
    "    at /Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:148:29",
    "    at fs.js:334:14",
    "    at FSReqWrap.oncomplete (fs.js:95:15)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-09-29 17:04:00.033 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v0.12.7",
"argv": [
    "node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images/demo",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.10",

"error": [
    "Error: w and h must be numbers",
    "    at Jimp.throwError (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:39:43)",
    "    at Jimp.resize (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:1010:20)",
    "    at Jimp.<anonymous> (/Users/vivaxy/code/github/preload-images/lib/image-builder.js:43:22)",
    "    at Jimp.parseBitmap (/Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:241:23)",
    "    at /Users/vivaxy/code/github/preload-images/node_modules/jimp/jimp.js:148:29",
    "    at fs.js:334:14",
    "    at FSReqWrap.oncomplete (fs.js:95:15)"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-12-23 21:10:38.488 +0800",
"arch": "x64",
"platform": "darwin",
"node-version": "v5.2.0",
"argv": [
    "/usr/local/bin/node",
    "/Users/vivaxy/code/github/preload-images/index.js"
],
"cwd": "/Users/vivaxy/code/github/preload-images/lib",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.12",

"error": [
    "Error: html not found",
    "    at main (/Users/vivaxy/code/github/preload-images/index.js:88:15)",
    "    at Object.<anonymous> (/Users/vivaxy/code/github/preload-images/index.js:118:1)",
    "    at Module._compile (module.js:399:26)",
    "    at Object.Module._extensions..js (module.js:406:10)",
    "    at Module.load (module.js:345:32)",
    "    at Function.Module._load (module.js:302:12)",
    "    at Function.Module.runMain (module.js:431:10)",
    "    at startup (node.js:141:18)",
    "    at node.js:977:3"
]
```

**Comment by vivaxy2012** [comment]
```json

"time": "2015-12-29 10:12:23.056 +0800",
"arch": "x64",
"platform": "win32",
"node-version": "v4.2.1",
"argv": [
    "E:\\Program Files\\nodejs\\node.exe",
    "C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\index.js"
],
"cwd": "C:\\Users\\king",
"usage-tracker-version": "1.1.4",

"preload-image-version": "1.5.12",

"error": [
    "Error: EPERM: operation not permitted, scandir 'C:\\Users\\king\\AppData\\Local\\Application Data'",
    "    at Error (native)",
    "    at Object.fs.readdirSync (fs.js:813:18)",
    "    at GlobSync._readdir (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:275:41)",
    "    at GlobSync._readdirInGlobStar (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:254:20)",
    "    at GlobSync._readdir (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:263:17)",
    "    at GlobSync._processReaddir (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:135:22)",
    "    at GlobSync._process (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:130:10)",
    "    at GlobSync._processGlobStar (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:360:10)",
    "    at GlobSync._process (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:128:10)",
    "    at GlobSync._processGlobStar (C:\\Users\\king\\AppData\\Roaming\\npm\\node_modules\\preload-images\\node_modules\\glob\\sync.js:363:10)"
]
```
